codecov:
  require_ci_to_pass: yes
  branch: master

coverage:
  precision: 2
  round: down
  range: "60..100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  branches:
    - master
  after_n_builds: 6  # 6 python versions for now: 3.7..3.12
