INDENT_SIZE: int = 4
INDENT_VALUE: str = " "
FUNC_BODY_INDENT: str = INDENT_VALUE * 2 * INDENT_SIZE
PARAM_PREFIX_TEMPLATE: str = f"{FUNC_BODY_INDENT}:param {{name}}: "
PARAM_SUBSEQUENT_INDENT: str = INDENT_VALUE * 3 * INDENT_SIZE
