INDENT_SIZE: int = 4
INDENT_VALUE: str = " "
REGULAR_INDENT: str = INDENT_VALUE * INDENT_SIZE
FUNC_BODY_INDENT: str = REGULAR_INDENT * 2
PARAM_PREFIX_TEMPLATE: str = f"{FUNC_BODY_INDENT}:param {{name}}: "
PARAM_SUBSEQUENT_INDENT: str = REGULAR_INDENT * 3
IN_FUNCTION_COMMENT: str = f"{FUNC_BODY_INDENT}# {{name}} - "
IN_FUNCTION_SUBSEQUENT_COMMENT: str = f"{FUNC_BODY_INDENT}#{REGULAR_INDENT}"
